### PR TITLE
Update libvips to 8.15.2

### PR DESCRIPTION
**Pull request by littleforest**

### CODE REVIEW

**Review by mike-burns — APPROVED** [review]
Nice.

**Comment by mike-burns** [comment]
The issue is that [the tarball](https://github.com/dhui5394/heroku-buildpack-vips/blob/master/container/Dockerfile.heroku-22#L98) contains `bin`, `lib`, and `include`, but libarchive-dev [installs into](https://packages.ubuntu.com/jammy/amd64/libarchive-dev/filelist) `/usr/lib/x86_64-linux-gnu/libarchive.so`.

Without deploying you can confirm that the result of `build.sh` is correct by making sure `libarchive.so` is in the tarball:

```sh
tar -ztf build/heroku-22.tar.gz | grep libarchive
```

**Comment by mike-burns** [comment]
I've forked to https://github.com/thoughtbot/heroku-buildpack-vips BTW.

**Comment by littleforest** [comment]
closing in favor of #51

**Pull request closed without merging**
