### PR TITLE
Support `heroku-22` stack

### PR DESCRIPTION
**Pull request by sgerrand**
💁 These changes add support for the `heroku-22` stack.

To test these changes I've successfully deployed some private Heroku apps using the `heroku-22` stack that are configured with this buildpack, but am interested to know what else could/would be useful for me to do to validate that these changes will work as expected.

### CODE REVIEW

**Comment by brandoncc** [comment]
Thank you for adding this. The one thing I also like to keep up to date is the config output in the readme. I will update that, since I'm also going to drop heroku-16 support.

**Comment by brandoncc** [comment]
I forgot to answer your question, sorry. I test the buildpacks the same way you did. I don't know of a better way, but I am open to suggestions if there is one.

**Comment by sgerrand** [comment]
> I test the buildpacks the same way you did. I don't know of a better way, but I am open to suggestions if there is one.

I think that the changes in your build script should broadly cover it, i.e. that `vips --vips-config` and `vips --vips-version` contain a set of expected strings in their output.

**Comment by sgerrand** [comment]
(Sorry for my delayed reply!)

**Pull request merged**
