### PR TITLE
Add text render feature

### PR DESCRIPTION
**Pull request by raykin**
Changes. text rendering with pangocairo: yes

### CODE REVIEW

**Comment by anitagraham** [comment]
+1 (x100)

**Comment by brandoncc** [comment]
Interesting. I will check this out, thanks for the PR!

**Comment by KELiON** [comment]
+1. Is there a way to use text rendering before this PR is merged?

**Comment by brandoncc** [comment]
Sorry I let this go for so long @raykin, could you rebase so that this PR can be merged?

**Comment by raykin** [comment]
@brandoncc Sorry. I've totally removed docker from my old mac cause I don't have enough space. I can rebase the PR only with config change. Then you can compile it to generate new tars if your docker instances are still available.

**Comment by brandoncc** [comment]
No problem @raykin, I just didn't want to take the commit away from you. I'm happy to make the change, build, and commit/merge it.

**Comment by brandoncc** [comment]
I actually had it ready to go because I replicated your work earlier today so that I could test the feature. I just created and merged [a PR](https://github.com/brandoncc/heroku-buildpack-vips/pull/30/files) for it. You should have pango on your next deploy!

**Pull request closed without merging**
